version: "3"

services:
  backend:
    build: ./src
    container_name: backend
    env_file:
      - ./src/.env
  frontend:
    build: ./public_html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/usr/share/nginx/html